BAU - Adding launch.json debug config for FAB
communitiesuk/funding-service-design-docker-runner pull request #96
Opened 2024-12-04 11:18 UTC by wjrm500

Quick change to add a debug configuration for the Fund Application Builder (FAB) application to `.vscode/launch.json` to allow developers to debug FAB locally.

2024-12-05 08:41 UTC, MarcUsher approved these changes
Ah good catch!

2024-12-06 13:07 UTC, MarcUsher requested changes
Ah I've just merged some tweaks to the launch.json so you prob need a rebase!

One small change request though - can I be annoying and ask if you can slot this a little higher up so the configs are in alphabetical order? 😅 

If you want you can also add it to the new `compounds` block at the end of the launch.json which means you can run that in the debugger and it'll attach the debugger to all the apps in the docker runner (if they're all up and running).

2024-12-06 18:13 UTC, wjrm500 commented
@MarcUsher only just seen your review! Yes of course, have made that change now. The compounds thing looks cool, I've popped FAB in there too

2024-12-09 09:31 UTC, MarcUsher approved these changes
Noice!

2024-12-09 10:19 UTC, merged